variables:
  versionbase: 3.22.25
  increment: $[counter(variables['versionbase'], 1)]
  version: $(versionbase).$(increment)

trigger:
  branches:
    include:
    - master
    - develop
  tags:
    include: 
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: ./build.sh --BuildTarget=FullBuild --BuildVersion=$(version)
  displayName: 'CAKE Script'
