
trigger:
  branches:
    include:
    - master
    - develop
  tags:
    include: 
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: ./build.sh --BuildTarget=FullBuild
  displayName: 'CAKE Script'
