variables:
  versionbase: 3.22.25
  increment: $[counter(variables['versionbase'], 1)]
  version: $(versionbase).$(increment)

trigger:
  branches:
    include:
    - master
    - develop
  tags:
    include: 
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: ./build.sh --BuildTarget=FullBuild --BuildVersion=$(version)
    displayName: 'CAKE Script'

  - task: PublishBuildArtifacts@1
    displayName: Publish Binaries
    inputs:
      pathtoPublish: BuildOutput/Release
      artifactName: Binaries
      publishLocation: container

  - task: PublishBuildArtifacts@1
    displayName: Publish NuGet
    inputs:
      pathtoPublish: BuildOutput/NugetPackages
      artifactName: NuGet
      publishLocation: container

  - task: PublishBuildArtifacts@1
    displayName: Publish Samples
    inputs:
      pathtoPublish: BuildOutput/Samples
      artifactName: Samples
      publishLocation: container